In [2]:
import numpy as np


In [7]:
#Task 01
arr = np.array([0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [18]:
arr[arr % 2 == 1]

array([11, 33, 55, 77, 99])

In [34]:
#Task 02
arr=np.array([0,11,22,33,44,55,66,77,88,99])

In [35]:
arr[arr%2==1]= -5
arr

array([ 0, -5, 22, -5, 44, -5, 66, -5, 88, -5])

In [64]:
#Task 03
arr=np.array([0,11 ,22 ,33 ,44 ,55 ,66 ,77 ,88 ,99])
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
out=np.where(arr%2==1, -5, arr)
out

array([ 0, -5,  2, -5,  4, -5,  6, -5,  8, -5])

In [67]:
#Task 04
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
arr=np.arange(20)
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [78]:
#Task 05
a=np.arange(20).reshape(2,-1)
b=np.repeat(1,20).reshape(2,-1)



In [79]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [80]:
#Task 06
a=np.arange(20).reshape(2,-1)
b=np.repeat(1,20).reshape(2,-1)

In [81]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1]])

In [83]:
#Task 07
a=np.array([1,2,3,4])

In [84]:
np.r_[np.repeat (a,4), np.tile(a,4)]

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [100]:
#Task 08
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,5,8])

In [101]:
np.intersect1d(a,b)

array([2, 4, 5])

In [117]:
#Task 09
a = np.array([1,2,3,4,5,6])
b = np.array([6,7,8,9,10])

In [118]:
np.setdiff1d(a,b)

array([1, 2, 3, 4, 5])

In [119]:
#Task 10
a=np.array([1,2,3,5,6,7,8,4,9])
b=np.array([1,3,3,4,6,8,7,4,5])

In [120]:
np.where(a==b)

(array([0, 2, 4, 7], dtype=int64),)

In [131]:
#Task 11
a=np.array([2,4,6,8,9,10,13,16,18])
np.arange(15)
a[(a>=4) &(a<=13)]

array([ 4,  6,  8,  9, 10, 13])

In [139]:
#Task 12
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 4, 6, 8, 6, 4, 5])
b = np.array([7, 3, 4, 8, 8, 7, 1])

pair_max(a, b)

array([7., 4., 6., 8., 8., 7., 5.])

In [20]:
import numpy as np

In [32]:
#Task 13
arr = np.arange(12).reshape(4,3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
arr[:,[1,0,2]]

array([[ 1,  0,  2],
       [ 4,  3,  5],
       [ 7,  6,  8],
       [10,  9, 11]])

In [34]:
#Task 14
arr = np.arange(12).reshape(4,3)

arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
arr[[1,0,2] ,:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [37]:
#Task 15
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
arr[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [40]:
#Task 16
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr[:, ::-1]

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

In [42]:
#Task 17
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
rand_arr=np.random.uniform(4,8, size=(4,4))
rand_arr

array([[5.78322928, 7.0944991 , 7.16038725, 5.13537696],
       [5.07752931, 6.55056696, 7.12640885, 5.88189143],
       [5.58705299, 7.66156827, 5.36060299, 6.51410032],
       [6.90866733, 7.13484235, 4.01195682, 6.56654201]])

In [55]:
#Task 18
rand_arr = np.random.random((4,8))

In [56]:
rand_arr = np.random.random([4,8])

In [70]:
np.set_printoptions(precision=4)
rand_arr[:3]

array([[0.5861, 0.88  , 0.0142, 0.2389, 0.5858, 0.0298, 0.0553, 0.5131],
       [0.9823, 0.4937, 0.2051, 0.6887, 0.4079, 0.4541, 0.5845, 0.5305],
       [0.8382, 0.7095, 0.8169, 0.0046, 0.2104, 0.8924, 0.7299, 0.149 ]])

In [81]:
#Task 19
np.random.seed(100)
rand_arr=np.random.random([4,4])/1e4
rand_arr

array([[5.4340e-05, 2.7837e-05, 4.2452e-05, 8.4478e-05],
       [4.7189e-07, 1.2157e-05, 6.7075e-05, 8.2585e-05],
       [1.3671e-05, 5.7509e-05, 8.9132e-05, 2.0920e-05],
       [1.8533e-05, 1.0838e-05, 2.1970e-05, 9.7862e-05]])

In [76]:
np.set_printoptions(suppress=False)

In [79]:
np.random.seed(100)

In [83]:
rand_arr=np.random.random([4,4])/1e4
rand_arr

array([[8.1168e-05, 1.7194e-05, 8.1622e-05, 2.7407e-05],
       [4.3170e-05, 9.4003e-05, 8.1765e-05, 3.3611e-05],
       [1.7541e-05, 3.7283e-05, 5.6885e-07, 2.5243e-05],
       [7.9566e-05, 1.5255e-06, 5.9884e-05, 6.0380e-05]])

In [85]:
np.set_printoptions(suppress=True, precision=8)
rand_arr

array([[0.00008117, 0.00001719, 0.00008162, 0.00002741],
       [0.00004317, 0.000094  , 0.00008176, 0.00003361],
       [0.00001754, 0.00003728, 0.00000057, 0.00002524],
       [0.00007957, 0.00000153, 0.00005988, 0.00006038]])

In [87]:
#Task 20
a=np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [88]:
np.set_printoptions(threshold=4)

In [89]:
a=np.arange(15)

In [90]:
a

array([ 0,  1,  2, ..., 10, 11, 12])

In [116]:
#Task 21
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])


In [118]:
np.percentile(sepallength, q=[3, 100])

array([4.547, 7.9  ])

In [120]:
#Task 22
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [121]:
np.random.seed(100)
iris_2d[np.random.randint(180, size=18), np.random.randint(6, size=18)] = np.nan

In [123]:
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [127]:
#Task 23
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 2
Position of missing values: 
 (array([33, 44], dtype=int64),)


In [129]:
#Task 24
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [130]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [138]:
#Task 25
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [144]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [145]:
#Task 26
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [146]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [147]:
#Task 27
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [148]:
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048714

In [149]:
#Task 28
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [150]:
np.isnan(iris_2d).any()

False

In [152]:
#Task 29
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(180, size=18), np.random.randint(6, size=18)] = np.nan

In [154]:
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [0. , 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [155]:
#Task 30
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [156]:
species = np.array([row.tolist()[4] for row in iris])


In [157]:
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50], dtype=int64))

In [158]:
#Task 31
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [159]:
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 9])

In [160]:
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

In [161]:
petal_length_cat[:4]

['small', 'small', 'small', 'small']

In [162]:
#Task 32
np.random.seed(103) 
arr = np.random.randint(1,5, size=8)
arr

array([4, 2, 4, ..., 3, 2, 1])

In [163]:
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]], dtype=int8)

In [165]:
#Task 33
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [166]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [167]:
#Task 34
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [168]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [169]:
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]

In [170]:
output = []
uniqs = np.unique(species_small)


In [172]:
for val in uniqs:  # uniq values in group
    for s in species_small[species_small==val]:  # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0]  # groupid
        output.append(groupid)

In [173]:
output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [6]:
import numpy as np

#Task 35
np.random.seed(10)
a = np.random.randint(20, size=20)
print(a)

[ 9  4 15  0 17 16 17  8  9  0 10  8  4 19 16  4 15 11 11  1]


In [7]:
print(a.argsort().argsort())
print('Array: ', a)

[ 9  3 13  1 17 15 18  6  8  0 10  7  5 19 16  4 14 12 11  2]
Array:  [ 9  4 15  0 17 16 17  8  9  0 10  8  4 19 16  4 15 11 11  1]


In [22]:
#Task 36
np.random.seed(10)
a = np.random.randint(25, size=[3,7])
print(a)

[[ 9  4 15  0 17 16 17]
 [ 8  9  0 10  8 22  4]
 [19 16  4 15 11 22 24]]


In [177]:
print(a.ravel().argsort().argsort().reshape(a.shape))


[[ 7  2 11 ... 15 13 16]
 [ 6  8  1 ...  5 19  4]
 [17 14  3 ... 10 18 20]]


In [178]:
#Task 37
np.random.seed(100)
a = np.random.randint(5,13, [6,2])
a

array([[ 5,  5],
       [ 8, 12],
       [12, 12],
       [ 5,  7],
       [11,  9],
       [ 7, 10]])

In [179]:
np.amax(a, axis=1)

array([ 5, 12, 12,  7, 11, 10])

In [180]:
#Task 38
np.random.seed(100)
a = np.random.randint(7,18, [7,4])
a

array([[15, 15, 10, 14],
       [14,  7, 17, 11],
       [ 9, 12,  9,  9],
       ...,
       [11, 17,  7, 16],
       [13,  9, 11,  8],
       [12, 10, 11, 11]])

In [181]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.66666667, 0.41176471, 0.75      , ..., 0.41176471, 0.61538462,
       0.83333333])

In [9]:
#Task 39
np.random.seed(100)
a = np.random.randint(0, 10, 15)
print('Array: ', a)

Array:  [8 8 3 7 7 0 4 2 5 2 2 2 1 0 8]


In [183]:
out = np.full(a.shape[0], True)

In [184]:
unique_positions = np.unique(a, return_index=True)[1]

In [185]:
out[unique_positions] = False

In [186]:
print(out)

[False  True False ... False  True  True]


In [187]:
#Task 40
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [188]:
numeric_column = iris[:, 1].astype('float')

In [189]:
grouping_column = iris[:, 4]

In [190]:
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [191]:
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

In [192]:
output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [15]:
#Task 41
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [16]:
from io import BytesIO
from PIL import Image
import PIL, requests

In [18]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

In [19]:
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])

In [20]:
arr = np.asarray(I)

In [21]:
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [202]:
#Task 42 
a = np.array([1,22,3,4,5])
b = np.array([4,5,66,7,8])

In [204]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [205]:
#Task 43
a = np.array([1, 3, 7, 1, 4, 5, 0, 1])

In [206]:
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

In [208]:
#Task 44
a_2d = np.array([[2,2,2],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [209]:
print(a_2d - b_1d[:,None])

[[1 1 1]
 [2 2 2]
 [2 2 2]]


In [210]:
#Task 45
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5


In [211]:
np.where(x == 1)[0][n-1]

8

In [212]:
#Task 46
dt64 = np.datetime64('2020-07-26 22:10:10')

In [218]:
from datetime import datetime
dt64.tolist()

datetime.datetime(2020, 7, 29, 23, 15, 15)

In [219]:
#Task 47
np.random.seed(100)
Z = np.random.randint(15, size=15)

In [220]:
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)

array:  [8 8 3 ... 2 5 2]


In [222]:
np.convolve(Z, np.ones(3)/3, mode='valid') 

array([6.33333333, 6.        , 5.66666667, ..., 2.        , 3.66666667,
       3.        ])

In [223]:
#Task 48
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, ..., 26, 29, 32])

In [224]:
#Task 49
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)


['2018-02-01' '2018-02-03' '2018-02-05' ... '2018-02-19' '2018-02-21'
 '2018-02-23']


In [225]:
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

In [226]:
output = np.hstack([filled_in, dates[-1]])
output

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [227]:
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)


In [228]:
output = np.hstack([filled_in, dates[-1]])
output

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [24]:
#Task 50
arr = np.arange(18) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [34]:
def gen_strides(a, stride_len=6, window_len=6):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(18), stride_len=3, window_len=5))

[[ 0  1  2  3  4]
 [ 3  4  5  6  7]
 [ 6  7  8  9 10]
 [ 9 10 11 12 13]
 [12 13 14 15 16]]
